# Generated by Django 4.1.7 on 2023-03-26 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('industry', models.CharField(choices=[('accounting', 'Accounting'), ('advertising', 'Advertising'), ('agriculture', 'Agriculture'), ('automotive', 'Automotive'), ('banking', 'Banking'), ('construction', 'Construction'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('insurance', 'Insurance'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('real-estate', 'Real Estate'), ('retail', 'Retail'), ('technology', 'Technology'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                ('job_category', models.CharField(choices=[('accounting', 'Accounting'), ('administrative', 'Administrative'), ('customer-service', 'Customer Service'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('human-resources', 'Human Resources'), ('information-technology', 'Information Technology'), ('marketing', 'Marketing'), ('sales', 'Sales')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirements', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('reviewer_rating', models.IntegerField()),
                ('review_content', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField()),
                ('application_status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
