# Generated by Django 4.1.7 on 2023-04-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_phone',
            new_name='phone',
        ),
    ]
