# Generated by Django 4.1.7 on 2023-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover',
            field=models.FileField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
