# Generated by Django 4.1.7 on 2023-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_cover_jobapplication_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
