# Generated by Django 4.1.7 on 2023-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_emailsubscription_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
    ]
